// Circuit visualizer (read-only).
//
// Renders the parsed `state.circuit` as a grid of qubit wires and gate boxes.
// Source of truth is the editor; this panel never mutates anything.
//
// Multi-qubit operations are emitted with shared `link` ids, so the renderer
// can draw one vertical connector for controlled gates, swaps, and other
// linked operations without hard-coding specific gate names.

use std::collections::BTreeMap;

use egui::{Color32, CornerRadius, FontId, Pos2, Rect, Sense, Stroke, StrokeKind, Vec2};

use crate::grid::Grid;
use crate::state::circuit::{GateKind, GatePlacement};
use crate::state::AppState;
use crate::theme::{color, space};

const BASE_CELL_W: f32 = 56.0;
const BASE_CELL_H: f32 = 48.0;
const LABEL_COL_W: f32 = 56.0;

pub fn show(ui: &mut egui::Ui, state: &mut AppState) {
    header(ui, state);
    ui.add_space(space::SM);

    egui::ScrollArea::both()
        .id_salt("circuit_scroll")
        .auto_shrink([false, false])
        .show(ui, |ui| draw_grid(ui, state));
}

fn header(ui: &mut egui::Ui, state: &mut AppState) {
    ui.horizontal(|ui| {
        ui.label(
            egui::RichText::new("circuit")
                .color(color::TEXT_MUTED)
                .monospace(),
        );
        ui.label(egui::RichText::new("·").color(color::TEXT_DIM));
        ui.label(
            egui::RichText::new(format!(
                "{}q × {}t",
                state.circuit.num_qubits, state.circuit.num_steps
            ))
            .color(color::TEXT_DIM)
            .monospace(),
        );
        ui.with_layout(egui::Layout::right_to_left(egui::Align::Center), |ui| {
            ui.label(
                egui::RichText::new(format!("{} gates", state.circuit.gates.len()))
                    .color(color::TEXT_DIM)
                    .monospace(),
            );
        });
    });
}

fn draw_grid(ui: &mut egui::Ui, state: &AppState) {
    let cell_w = BASE_CELL_W;
    let cell_h = BASE_CELL_H;
    let label_w = LABEL_COL_W;
    let cols = state.circuit.num_steps;
    let rows = state.circuit.num_qubits;
    let header_band = 14.0;

    let total_w = label_w + cols as f32 * cell_w + 8.0;
    let total_h = (rows as f32 * cell_h + header_band + 8.0).max(60.0);

    let (rect, _) = ui.allocate_exact_size(Vec2::new(total_w, total_h), Sense::hover());
    let painter = ui.painter_at(rect);

    // Step header
    for c in 0..cols {
        if c % 2 == 0 {
            let x = rect.min.x + label_w + (c as f32 + 0.5) * cell_w;
            painter.text(
                Pos2::new(x, rect.min.y + 4.0),
                egui::Align2::CENTER_TOP,
                format!("{c}"),
                FontId::monospace(10.0),
                color::TEXT_DIM,
            );
        }
    }

    let origin = Pos2::new(rect.min.x + label_w, rect.min.y + header_band);
    let grid = Grid::new(origin, Vec2::new(cell_w, cell_h), cols, rows);

    // Qubit labels
    for r in 0..rows {
        let y = grid.row_y(r);
        painter.text(
            Pos2::new(rect.min.x + label_w * 0.5, y),
            egui::Align2::CENTER_CENTER,
            format!("q{r}"),
            FontId::monospace(13.0),
            color::TEXT_MUTED,
        );
    }

    // Wires
    for r in 0..rows {
        let y = grid.row_y(r);
        painter.line_segment(
            [Pos2::new(origin.x, y), Pos2::new(origin.x + cols as f32 * cell_w, y)],
            Stroke::new(1.0, color::WIRE),
        );
    }

    // Vertical step guides
    for c in 0..=cols {
        let x = origin.x + c as f32 * cell_w;
        painter.line_segment(
            [
                Pos2::new(x, origin.y),
                Pos2::new(x, origin.y + rows as f32 * cell_h),
            ],
            Stroke::new(0.5, color::GRID_LINE),
        );
    }

    // Multi-qubit connectors (`link` ids generated by the parser).
    let mut groups: BTreeMap<usize, Vec<&GatePlacement>> = BTreeMap::new();
    for gate in &state.circuit.gates {
        if let Some(link) = gate.link {
            groups.entry(link).or_default().push(gate);
        }
    }
    for group in groups.values() {
        if group.len() < 2 {
            continue;
        }
        let step = group[0].step;
        let min_q = group.iter().map(|g| g.qubit).min().unwrap_or(0);
        let max_q = group.iter().map(|g| g.qubit).max().unwrap_or(0);
        if min_q < rows && max_q < rows && step < cols {
            let x = grid.col_x(step);
            let y_top = grid.row_y(min_q);
            let y_bot = grid.row_y(max_q);
            painter.line_segment(
                [Pos2::new(x, y_top), Pos2::new(x, y_bot)],
                Stroke::new(1.0, color::TEXT_PRIMARY),
            );
        }
    }

    // Gate boxes
    for g in &state.circuit.gates {
        if g.qubit >= rows || g.step >= cols {
            continue;
        }
        draw_gate(&painter, &grid, g);
    }
}

fn draw_gate(painter: &egui::Painter, grid: &Grid, gate: &GatePlacement) {
    let center = grid.cell_center(gate.step, gate.qubit);
    let side = grid.cell.x.min(grid.cell.y) * 0.62;
    let rect = Rect::from_center_size(center, Vec2::splat(side));

    match gate.kind {
        GateKind::Control => {
            painter.circle_filled(center, 5.0, color::TEXT_PRIMARY);
        }
        GateKind::Measure => {
            painter.rect_filled(rect, CornerRadius::same(4), color::BG_ELEVATED);
            painter.rect_stroke(
                rect,
                CornerRadius::same(4),
                Stroke::new(1.0, color::ACCENT_RED),
                StrokeKind::Inside,
            );
            painter.text(
                center,
                egui::Align2::CENTER_CENTER,
                "M",
                FontId::monospace(15.0),
                color::ACCENT_RED,
            );
        }
        _ => {
            let fg = color::ACCENT_YELLOW;
            let label = gate.display_label();
            let font_size = match label.len() {
                0 | 1 => 15.0,
                2 => 13.0,
                3 => 11.0,
                _ => 10.0,
            };
            painter.rect_filled(rect, CornerRadius::same(4), color::BG_ELEVATED);
            painter.rect_stroke(
                rect,
                CornerRadius::same(4),
                Stroke::new(1.0, fg),
                StrokeKind::Inside,
            );
            painter.text(
                center,
                egui::Align2::CENTER_CENTER,
                label,
                FontId::monospace(font_size),
                fg,
            );
        }
    }

    // Suppress unused-warnings for transparent fill in some configs.
    let _ = Color32::TRANSPARENT;
}
